version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  frontend:
    image: isv1601/foodgram_frontend
    volumes:
      - static:/result_build/
    depends_on:
      - backend

  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    image: isv1601/foodgram_backend
    volumes:
      - static:/backend_static
      - media:/app/media
    env_file:
      - ../.env
    depends_on:
      - db

  nginx:
    image: nginx:1.22.1
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/app/media
    depends_on:
      - backend
      - frontend